apiVersion: v1
kind: Service
metadata:
  name: address-service-testing
  labels:
    app: address
    env: testing
spec:
  selector:
    app: address
    env: testing
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31100
  type: NodePort
