apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: address-deployment-staging
  labels:
    app: address
    env: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: address
        env: staging
    spec:
      containers:
      - name: address-staging
        image: ADDRESS_CONTAINER_IMAGE
        ports:
        - name: http-port
          containerPort: 8080
        volumeMounts:
        - name: address-logback-volume
          mountPath: /etc/address
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: staging
          - name: JVM_ARGS
            value: "-Xmx256m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
          successThreshold: 1
          timeoutSeconds: 3
      volumes:
      - name: address-logback-volume
        configMap:
          name: address-logback-staging-configmap
