podTemplate(label: 'acceptance', 
  containers: [
    containerTemplate(name: 'maven', image: 'maven:3.3.9-jdk-8-alpine', ttyEnabled: true, command: 'cat')
  ],
  volumes: [
    secretVolume(mountPath: '/etc/maven/', secretName: 'maven-settings-secret')
  ])
{
  node ('acceptance') {

    stage('Checkout the Address application') {
      git url: 'https://github.com/ivanp81/address.git', branch: "${GIT_BRANCH}"
    }
    
    stage('Run Acceptance Tests') {
      container('maven') {
      	sh """
          mvn -B -s /etc/maven/settings.xml clean verify -Pacceptance-tests -Dacceptance.address.url=${ADDRESS_URL} -Dsurefire.rerunFailingTestsCount=3
        """
      }
    }
  }
}
